version: 2.1

orbs:
  node: circleci/node@5.0.2
  # codecov: codecov/codecov@4.0.1

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: compile tsc
          command: npm run build
      - run:
          name: Run tests
          command: npm run test

workflows:
  # version: 2
  # upload-to-codecov:
  #   jobs:
  #     - test-node
  #     - codecov/upload:
  #         requires:
  #           - test-node
  build-and-test:
    jobs:
      - test-node
