version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          command: npm run build
      - run:
          command: npm run test
    environment:
      JWT_SECRET: secrettoken

workflows:
  build-and-test:
    jobs:
      - test-node
